---
deployment:
  tasks:
    - export PROD=/home/zahidinn/public_html
    - export DEV=/home/zahidinn/public_html/dev
    - /bin/cp -R dist/* $PROD
    - /bin/cp -R dist/.[!.]* $PROD
    - /bin/cp -R dist/* $DEV
    - /bin/cp -R dist/.[!.]* $DEV
